### ISSUE TITLE
平滑重启的过程中报错：panic: accept tcp [::]:1991: use of closed network connection

### ISSUE THREAD

**Issue by buexplain** [tabalt/gracehttp#12]
## vi main.go
```golang
package main

import (
	"github.com/tabalt/gracehttp"
	"log"
	"net/http"
	"os"
	"strconv"
	"time"
)

func main() {
	mux := http.NewServeMux()

	mux.HandleFunc("/slow", func(writer http.ResponseWriter, request *http.Request) {
		_ = request.ParseForm()
		t, _ := strconv.Atoi(request.Form.Get("ms"))
		if t > 0 {
			<- time.After(time.Duration(t)*time.Millisecond)
		}
		writer.WriteHeader(http.StatusOK)
		_, _ = writer.Write([]byte(strconv.Itoa(os.Getpid())))
	})

	server := gracehttp.NewServer(":1991", mux, 60 * time.Second, 60 * time.Second)

	log.Panicln(server.ListenAndServe())
}
```

## 运行
```bash
go build main.go && ./main
```

## 测试
```bash
kill -SIGUSR2 5646
```

## 错误
```bash
2019/06/10 16:51:02 pid 5646 received SIGUSR2.
2019/06/10 16:51:02 graceful restart http server...
2019/06/10 16:51:02 start new process success, pid 5664.
2019/06/10 16:51:02 waiting for connection close...
2019/06/10 16:51:02 all connection closed, process with pid 5646 shutting down...
2019/06/10 16:51:02 listener of pid 5646 closed.
2019/06/10 16:51:02 accept tcp [::]:1991: use of closed network connection
panic: accept tcp [::]:1991: use of closed network connection


goroutine 1 [running]:
log.Panicln(0xc0000c9f78, 0x1, 0x1)
	/usr/local/go/src/log/log.go:347 +0xac
main.main()
	/opt/www/testgo-x/main.go:27 +0x109
```

**Comment by buexplain** [comment]
> ```shell
> 
> 2
> ```



> ## vi main.go
> ```go
> package main
> 
> import (
> 	"github.com/tabalt/gracehttp"
> 	"log"
> 	"net/http"
> 	"os"
> 	"strconv"
> 	"time"
> )
> 
> func main() {
> 	mux := http.NewServeMux()
> 
> 	mux.HandleFunc("/slow", func(writer http.ResponseWriter, request *http.Request) {
> 		_ = request.ParseForm()
> 		t, _ := strconv.Atoi(request.Form.Get("ms"))
> 		if t > 0 {
> 			<- time.After(time.Duration(t)*time.Millisecond)
> 		}
> 		writer.WriteHeader(http.StatusOK)
> 		_, _ = writer.Write([]byte(strconv.Itoa(os.Getpid())))
> 	})
> 
> 	server := gracehttp.NewServer(":1991", mux, 60 * time.Second, 60 * time.Second)
> 
> 	log.Panicln(server.ListenAndServe())
> }
> ```
> 
> ## 运行
> ```shell
> go build main.go && ./main
> ```
> 
> ## 测试
> ```shell
> kill -SIGUSR2 5646
> ```
> 
> ## 错误
> ```shell
> 2019/06/10 16:51:02 pid 5646 received SIGUSR2.
> 2019/06/10 16:51:02 graceful restart http server...
> 2019/06/10 16:51:02 start new process success, pid 5664.
> 2019/06/10 16:51:02 waiting for connection close...
> 2019/06/10 16:51:02 all connection closed, process with pid 5646 shutting down...
> 2019/06/10 16:51:02 listener of pid 5646 closed.
> 2019/06/10 16:51:02 accept tcp [::]:1991: use of closed network connection
> panic: accept tcp [::]:1991: use of closed network connection
> 
> 
> goroutine 1 [running]:
> log.Panicln(0xc0000c9f78, 0x1, 0x1)
> 	/usr/local/go/src/log/log.go:347 +0xac
> main.main()
> 	/opt/www/testgo-x/main.go:27 +0x109
> ```

我知道怎么回事了，是程序结束的时候我自己log.Panicln了一下。
